config/routes.rb
Rails.application.routes.draw do
  root 'gigs#index'

  resources :gigs, only: %i[index show] do
    get 'past', to: 'gigs#past', on: :collection
  end

  resources :subscribers, only: %i[create]

  namespace :admin do
    resources :gigs do
      collection do
        get 'social_post', to: 'gigs#social_post'
      end
    end
    resources :venues
    resources :subscribers
    resources :acts

    root to: 'gigs#index'
  end
end

app/models/gig.rb
class Gig < ApplicationRecord
  has_many :acts_gig
  has_many :acts, through: :acts_gig

  def doors_time_only
    doors&.strftime('%l:%M%P')
  end

  def date
    # This is to faciliate the different between dev and prod
    # in dev we use sqlite which stores dates as strings, in prod
    # we use postgres which stores dates as datetimes
    return Date.parse(self[:date]) if self[:date].is_a?(String)

    self[:date]
  end
end

app/controllers/admin/gigs_controller.rb
module Admin
  class GigsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information

    def social_post
      @start_date = Date.parse(params[:start_date]) rescue nil
      @end_date = Date.parse(params[:end_date]) rescue nil

      if @start_date && @end_date
        @days = Gig.where(date: @start_date..@end_date)
                   .order(date: :asc, doors: :asc)
                   .group_by { |gig| gig.date }
      end
    end
  end
end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController
  before_action :set_gig, only: %i[show edit update destroy]

  # GET /gigs or /gigs.json
  def index
    @subscriber = Subscriber.new
    @gigs = Gig.all.order(date: :asc)
      .where("date >= ?", Date.today)
  end

  def past
    @subscriber = Subscriber.new
    @gigs = Gig.all.order(date: :desc)
      .where("date < ?", Date.today)
  end

  # GET /gigs/1 or /gigs/1.json
  def show; end

  # GET /gigs/new
  def new
    @gig = Gig.new
  end

  # GET /gigs/1/edit
  def edit; end

  # POST /gigs or /gigs.json
  def create
    @gig = Gig.new(gig_params)

    respond_to do |format|
      if @gig.save
        format.html { redirect_to gig_url(@gig), notice: 'Gig was successfully created.' }
        format.json { render :show, status: :created, location: @gig }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gigs/1 or /gigs/1.json
  def update
    respond_to do |format|
      if @gig.update(gig_params)
        format.html { redirect_to gig_url(@gig), notice: 'Gig was successfully updated.' }
        format.json { render :show, status: :ok, location: @gig }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gigs/1 or /gigs/1.json
  def destroy
    @gig.destroy

    respond_to do |format|
      format.html { redirect_to gigs_url, notice: 'Gig was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_gig
    @gig = Gig.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def gig_params
    params.require(:gig).permit(:name)
  end
end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/views/admin/gigs/_collection.html.erb
<%#
# Collection

This partial is used on the `index` and `show` pages
to display a collection of resources in an HTML table.

## Local variables:

- `collection_presenter`:
  An instance of [Administrate::Page::Collection][1].
  The table presenter uses `ResourceDashboard::COLLECTION_ATTRIBUTES` to determine
  the columns displayed in the table
- `resources`:
  An ActiveModel::Relation collection of resources to be displayed in the table.
  By default, the number of resources is limited by pagination
  or by a hard limit to prevent excessive page load times

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<table aria-labelledby="<%= table_title %>">
  <thead>
    <tr>
      <% collection_presenter.attribute_types.each do |attr_name, attr_type| %>
        <th class="cell-label
        cell-label--<%= attr_type.html_class %>
        cell-label--<%= collection_presenter.ordered_html_class(attr_name) %>
        cell-label--<%= "#{collection_presenter.resource_name}_#{attr_name}" %>"
        scope="col"
        role="columnheader"
        aria-sort="<%= sort_order(collection_presenter.ordered_html_class(attr_name)) %>">
        <%= link_to(sanitized_order_params(page, collection_field_name).merge(
          collection_presenter.order_params_for(attr_name, key: collection_field_name)
        )) do %>
        <%= t(
          "helpers.label.#{collection_presenter.resource_name}.#{attr_name}",
          default: resource_class.human_attribute_name(attr_name),
        ).titleize %>
            <% if collection_presenter.ordered_by?(attr_name) %>
              <span class="cell-label__sort-indicator cell-label__sort-indicator--<%= collection_presenter.ordered_html_class(attr_name) %>">
                <svg aria-hidden="true">
                  <use xlink:href="#icon-up-caret" />
                </svg>
              </span>
            <% end %>
          <% end %>
        </th>
      <% end %>
      <%= render(
        "collection_header_actions",
        collection_presenter: collection_presenter,
        page: page,
        resources: resources,
        table_title: "page-title"
      ) %>
    </tr>
  </thead>

  <tbody>
    <% resources.each do |resource| %>
      <tr class="js-table-row"
          <% if accessible_action?(resource, :show) %>
            <%= %(tabindex=0 role=link data-url=#{polymorphic_path([namespace, resource])}) %>
          <% end %>
          >
        <% collection_presenter.attributes_for(resource).each do |attribute| %>
          <td class="cell-data cell-data--<%= attribute.html_class %>">
            <% if accessible_action?(resource, :show) -%>
              <a href="<%= polymorphic_path([namespace, resource]) -%>"
                 tabindex="-1"
                 class="action-show"
                 >
                <%= render_field attribute %>
              </a>
            <% else %>
              <%= render_field attribute %>
            <% end -%>
          </td>
        <% end %>

        <%= render(
          "collection_item_actions",
          collection_presenter: collection_presenter,
          collection_field_name: collection_field_name,
          page: page,
          namespace: namespace,
          resource: resource,
          table_title: "page-title"
        ) %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/gigs/_index_header.html.erb
<% content_for(:title) do %>
  <%= display_resource_name(page.resource_name) %>
<% end %>

<header class="main-content__header">
  <h1 class="main-content__page-title" id="page-title">
    <%= content_for(:title) %>
  </h1>

  <% if show_search_bar %>
    <%= render(
      "search",
      search_term: search_term,
      resource_name: display_resource_name(page.resource_name)
    ) %>
  <% end %>

  <div>
    <%= link_to(
      t(
        "administrate.actions.new_resource",
        name: display_resource_name(page.resource_name, singular: true).downcase
      ),
      [:new, namespace, page.resource_path.to_sym],
      class: "button",
    ) if accessible_action?(new_resource, :new) %>

    <%= link_to(
      "New Social Post",
      [:social_post, namespace, :gigs],
      class: "button"
    ) if accessible_action?(new_resource, :social_post) %>
  </div>
</header>

app/views/admin/gigs/index.html.erb
<%#
# Index

This view is the template for the index page.
It is responsible for rendering the search bar, header and pagination.
It renders the `_table` partial to display details about the resources.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Collection][1].
  Contains helper methods to help display a table,
  and knows which attributes should be displayed in the resource's table.
- `resources`:
  An instance of `ActiveRecord::Relation` containing the resources
  that match the user's search criteria.
  By default, these resources are passed to the table partial to be displayed.
- `search_term`:
  A string containing the term the user has searched for, if any.
- `show_search_bar`:
  A boolean that determines if the search bar should be shown.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<%=
  render("index_header",
    resources: resources,
    search_term: search_term,
    page: page,
    show_search_bar: show_search_bar,
  )
%>

<section class="main-content__body main-content__body--flush">
  <%= render(
    "collection",
    collection_presenter: page,
    collection_field_name: resource_name,
    page: page,
    resources: resources,
    table_title: "page-title"
  ) %>

  <%= render("pagination", resources: resources) %>
</section>

app/views/admin/gigs/social_post.html.erb
<header class="main-content__header flex">
  <h1 class="main-content__page-title"  id="page-title">
    Social Post
  </h1>

  <%= form_with url: social_post_admin_gigs_path, method: :get, class: '' do |form| %>
    <div class="flex space-x-4 items-center">

      <div>
        <%= form.label :start_date %>
        <%= form.date_field :start_date %>
      </div>

      <div>
        <%= form.label :end_date %>
        <%= form.date_field :end_date %>
      </div>
      <%= form.submit "Create", class: "px-3 py-2 h-auto" %>
    </div>
  <% end %>
</header>

<div class="p-4">
  <% if @days %>
    <h2>
      <% if @start_date.month != @end_date.month %>
        <%= @start_date.day %> <%= @start_date.strftime("%b").upcase %> - <%= @end_date.day %> <%= @end_date.strftime("%b").upcase %>
      <% else %>
        <%= @start_date.day %>-<%= @end_date.day %> <%= @end_date.strftime("%b").upcase %>
      <% end %>
    </h2>

    <div>
      <% @days.each do |day, gigs| %>
        <br/>
        <div><%= day.strftime("%a %d %b").upcase %></div>

        <div>
          <% gigs.each do |gig| %>
            <br/>
            <div><%= gig.name %><div/>
            <div><%= gig.venue %></div>
            <div><%= gig.doors.strftime("%l:%M%p").strip.downcase %></div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>