config/routes.rb
Rails.application.routes.draw do
  root 'gigs#index'

  resources :gigs, only: %i[index show] do
    get 'past', to: 'gigs#past', on: :collection
  end

  resources :subscribers, only: %i[create]

  namespace :admin do
    resources :gigs do
      collection do
        get 'social_post', to: 'gigs#social_post'
      end
    end
    resources :venues
    resources :subscribers
    resources :acts

    root to: 'gigs#index'
  end
end

app/models/gig.rb
class Gig < ApplicationRecord
  has_many :acts_gig
  has_many :acts, through: :acts_gig

  def doors_time_only
    doors&.strftime('%l:%M%P')
  end

  def date
    # This is to faciliate the different between dev and prod
    # in dev we use sqlite which stores dates as strings, in prod
    # we use postgres which stores dates as datetimes
    return Date.parse(self[:date]) if self[:date].is_a?(String)

    self[:date]
  end
end

app/controllers/admin/gigs_controller.rb
module Admin
  class GigsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information

    def social_post
      @start_date = Date.parse(params[:start_date]) rescue nil
      @end_date = Date.parse(params[:end_date]) rescue nil

      if @start_date && @end_date
        @days = Gig.where(date: @start_date..@end_date)
                   .order(date: :asc, doors: :asc)
                   .group_by { |gig| gig.date }
      end
    end
  end
end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController
  before_action :set_gig, only: %i[show edit update destroy]

  # GET /gigs or /gigs.json
  def index
    @subscriber = Subscriber.new
    @gigs = Gig.all.order(date: :asc)
      .where("date >= ?", Date.today)
  end

  def past
    @subscriber = Subscriber.new
    @gigs = Gig.all.order(date: :desc)
      .where("date < ?", Date.today)
  end

  # GET /gigs/1 or /gigs/1.json
  def show; end

  # GET /gigs/new
  def new
    @gig = Gig.new
  end

  # GET /gigs/1/edit
  def edit; end

  # POST /gigs or /gigs.json
  def create
    @gig = Gig.new(gig_params)

    respond_to do |format|
      if @gig.save
        format.html { redirect_to gig_url(@gig), notice: 'Gig was successfully created.' }
        format.json { render :show, status: :created, location: @gig }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gigs/1 or /gigs/1.json
  def update
    respond_to do |format|
      if @gig.update(gig_params)
        format.html { redirect_to gig_url(@gig), notice: 'Gig was successfully updated.' }
        format.json { render :show, status: :ok, location: @gig }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gigs/1 or /gigs/1.json
  def destroy
    @gig.destroy

    respond_to do |format|
      format.html { redirect_to gigs_url, notice: 'Gig was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_gig
    @gig = Gig.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def gig_params
    params.require(:gig).permit(:name)
  end
end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/views/gigs/_form.html.erb
<%= form_with(model: gig, class: "contents") do |form| %>
  <% if gig.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(gig.errors.count, "error") %> prohibited this gig from being saved:</h2>

      <ul>
        <% gig.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/gigs/_gig.html.erb
<div id="<%= dom_id gig %>">
  <p class="text-xl">
    <%= gig.name %>
  </p>
  <p>
    <%= gig.venue %>
  </p>
  <p>
    <%= gig.doors_time_only %>
  </p>

  <p>
  <% if link_acts %>
    <%= gig.acts.map { |act| act.weblink.blank? ? act.name : link_to(act.name, act.weblink, class: 'underline') }.join(", ").html_safe %>
  <% else %>
    <%= @link_acts %>
    <%= gig.acts.map { |act| act.name }.join(", ").html_safe %>
  <% end %>
  </p>

  <p>
    <%= gig.socials %>
  </p>
</div>

app/views/gigs/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing gig</h1>

  <%= render "form", gig: @gig %>

  <%= link_to "Show this gig", @gig, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to gigs", gigs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/gigs/index.html.erb
<% content_for(:nav) do %>
  <%= link_to('Past Gigs', past_gigs_path, class: 'text-center underline text-lg') %>
<% end %>


<div class="w-full">
  <div class="p-8 space-y-8 bg-black bg-chalk-board">
    <h2 class="text-8xl uppercase text-white text-center font-display">
      What's on this week?
    </h2>
    <h3 class="text-xl text-white text-center">
      <% if notice.present? %>
        <span id="notice"><%= notice %></span>
      <% else %>
        Join the mailing list!
      <% end %>
    </h3>
    <%= form_with(model: @subscriber) do |form| %>
      <% if @subscriber.errors.any? %>
        <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
          <h2><%= pluralize(@subscriber.errors.count, "error") %> prohibited creating a subscription:</h2>

          <ul>
            <% subscription.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>


      <div class="my-5 flex max-w-lg mx-auto">
        <%= form.text_field :email, placeholder: "Email", class: "block shadow rounded-l-lg border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
        <%= form.submit "Subscribe", class: "rounded-r-lg mt-2 py-2 px-3 bg-blue-600 text-white inline-block font-medium cursor-pointer border-1 border-blue-600" %>
      </div>
    <% end %>
  </div>

  <div class="px-6">

    <div id="gigs" class="min-w-full">
      <% previous_gig = nil %>
      <% ad_rate = 7 %>
      <% @gigs.each do |gig| %>
        <% if previous_gig.nil? || gig.date != previous_gig.date %>
          <% ad_rate = ad_rate > 0 ? ad_rate - 1 : 7 %>
          <% if ad_rate == 3 %>
            <%= link_to "https://badhabitstudios.co.uk", class: "-ml-2 block bg-black text-white hover:bg-gray-800 p-2 mt-5" do %>
              <span class="py-5 text-2xl text-center">Bad Habit Studios</span>
              <br/>
              <span>Music rehearsal &amp; recording studio in Eastbourne</span>
            <% end %>
          <% end %>
          <%= link_to "##{gig.date}", class: "underline" do %>
            <h3 class="text-3xl mt-5" data-date="<%= gig.date %>" id="<%= gig.date %>">
              <%= gig.date&.strftime("%^a %-d %^b") %>
            </h3>
          <% end %>
        <% end %>
        <% previous_gig = gig %>
        <%= link_to gig, class: "-ml-2 block bg-gray-100 hover:bg-gray-200 p-2 mt-5" do %>
          <%= render partial: 'gig', locals: { gig: gig, link_acts: false } %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/gigs/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New gig</h1>

  <%= render "form", gig: @gig %>

  <%= link_to 'Back to gigs', gigs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/gigs/past.html.erb
<% content_for(:nav) do %>
  <%= link_to('Current Gigs', gigs_path, class: 'text-center underline text-lg') %>
<% end %>

<div class="w-full">

  <div class="p-8 space-y-8 bg-black bg-chalk-board">
    <h2 class="text-8xl uppercase text-white text-center font-display">
      Gigs of times gone past
    </h2>

    <h3 class="text-xl text-white text-center">
      <% if notice.present? %>
        <span id="notice"><%= notice %></span>
      <% else %>
        Join the mailing list!
      <% end %>
    </h3>
    <%= form_with(model: @subscriber) do |form| %>
      <% if @subscriber.errors.any? %>
        <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
          <h2><%= pluralize(@subscriber.errors.count, "error") %> prohibited creating a subscription:</h2>

          <ul>
            <% subscription.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>


      <div class="my-5 flex max-w-lg mx-auto">
        <%= form.text_field :email, placeholder: "Email", class: "block shadow rounded-l-lg border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
        <%= form.submit "Subscribe", class: "rounded-r-lg mt-2 py-2 px-3 bg-blue-600 text-white inline-block font-medium cursor-pointer border-1 border-blue-600" %>
      </div>
    <% end %>
  </div>

  <div id="gigs" class="min-w-full px-6">
    <% previous_gig = nil %>
    <% @gigs.each do |gig| %>
      <% if previous_gig.nil? || gig.date != previous_gig.date %>
        <%= link_to "##{gig.date}", class: "underline" do %>
          <h3 class="text-3xl mt-5" data-date="<%= gig.date %>" id="<%= gig.date %>">
            <%= gig.date&.strftime("%^a %-d %^b") %>
          </h3>
        <% end %>
      <% end %>
      <% previous_gig = gig %>
      <%= link_to gig, class: "-ml-2 block bg-gray-100 hover:bg-gray-200 p-2 mt-5" do %>
        <%= render partial: 'gig', locals: { gig: gig, link_acts: false } %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/gigs/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render partial: 'gig', locals: { gig: @gig, link_acts: true } %>
  </div>
</div>